name: CI Build & Test
# Triggers the workflow on push or pull request events
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          # macOS builds
          # ~~~~~~~~~~~~
          - name: macOS-13/Xcode/Debug
            build_type: Debug
            generator: Xcode
            options: -D URI_CXX17=No
            os: macos-13

          - name: macOS-13/Xcode/Release
            build_type: Release
            generator: Xcode
            options: -D URI_CXX17=No
            os: macos-13

          # Linux builds
          # ~~~~~~~~~~~~
          - name: Ubuntu-22.04/gcc-11/Debug
            apt_install: cmake ninja-build
            build_type: Debug
            generator: Ninja
            options: -D URI_CXX17=No
            os: ubuntu-22.04

          - name: Ubuntu-22.04/gcc-11/Release
            apt_install: cmake ninja-build
            build_type: Release
            generator: Ninja
            options: -D URI_CXX17=No
            os: ubuntu-22.04

          - name: Ubuntu-22.04/clang-15/Debug
            apt_install: clang-15 cmake libc++-15-dev libc++abi-15-dev ninja-build
            build_type: Debug
            cxx_compiler: -D CMAKE_CXX_COMPILER=clang++-15 -D CMAKE_C_COMPILER=clang-15
            generator: Ninja
            options: -D URI_CXX17=No -D URI_LIBCXX=Yes -D CMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold
            os: ubuntu-22.04

          - name: Ubuntu-22.04/clang-15/Release
            apt_install: clang-15 cmake libc++-15-dev libc++abi-15-dev ninja-build
            build_type: Release
            cxx_compiler: -D CMAKE_CXX_COMPILER=clang++-15 -D CMAKE_C_COMPILER=clang-15
            generator: Ninja
            options: -D URI_CXX17=No -D URI_LIBCXX=Yes -D CMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold
            os: ubuntu-22.04

          # Windows builds
          # ~~~~~~~~~~~~~~
          - name: Windows-latest/VS2022/Debug
            build_type: Debug
            generator: Visual Studio 17 2022
            options: -D URI_CXX17=No
            os: windows-latest

          - name: Windows-latest/VS2022/Release
            build_type: Release
            generator: Visual Studio 17 2022
            options: -D URI_CXX17=No
            os: windows-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: 'True'

      - name: Install Dependencies (Linux)
        if: startsWith (matrix.os, 'ubuntu-') && matrix.apt_install != ''
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.apt_install }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S "$GITHUB_WORKSPACE"                       \
                -B "${{ github.workspace }}/build"           \
                -G "${{ matrix.generator }}"                 \
                -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -D URI_WERROR=Yes                            \
                ${{ matrix.cxx_compiler }}                   \
                ${{ matrix.options }}

      - name: Build
        shell: bash
        run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.build_type }}
