name: CodeCov
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_codecov
      GCC_VERSION: 12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'True'

      - name: Install libc++, libc++abc, and ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure build
        run: |
          mkdir "$BUILD_DIR"
          cmake                                      \
            -G Ninja                                 \
            -S .                                     \
            -B "$BUILD_DIR"                          \
            -D COVERAGE=Yes                          \
            -D CMAKE_C_COMPILER="gcc-$GCC_VERSION"   \
            -D CMAKE_CXX_COMPILER="g++-$GCC_VERSION"

      - name: Build
        run: |
            cmake --build "$BUILD_DIR"

      #- name: Collect the coverage
      #  run: |
      #    "llvm-cov-$CLANG_VERSION" show \
      #      --instr-profile "$BUILD_DIR/merged.profdata" \
      #      "$BUILD_DIR/unittests/pj-unittests" > coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
