name: CodeCov
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_codecov
      GCC_VERSION: 12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'True'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov ninja-build

      - name: Configure Build
        run: |
          mkdir "$BUILD_DIR"
          cmake                                      \
            -G Ninja                                 \
            -S .                                     \
            -B "$BUILD_DIR"                          \
            -D COVERAGE=Yes                          \
            -D CMAKE_C_COMPILER="gcc-$GCC_VERSION"   \
            -D CMAKE_CXX_COMPILER="g++-$GCC_VERSION"

      - name: Build
        run: |
            cmake --build "$BUILD_DIR"

      - name: Collect the Coverage
        run: |
          set -x
          lcov                              \
            --capture                       \
            --output-file coverage.info     \
            --directory "$BUILD_DIR"        \
            --gcov-tool "gcov-$GCC_VERSION" \
            --include "$(pwd)/*.?pp"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
