name: Fuzz Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  fuzztest:
    name: Fuzz Test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_fuzztest
      CLANG_VERSION: 16

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y            \
            "clang-${CLANG_VERSION}"         \
            cmake                            \
            "libc++-${CLANG_VERSION}-dev"    \
            "libc++abi-${CLANG_VERSION}-dev"

      - name: Configure
        run: |
          mkdir "$BUILD_DIR"
          cmake                                            \
            -S .                                           \
            -B "$BUILD_DIR"                                \
            -D CMAKE_BUILD_TYPE=RelWithDebug               \
            -D CMAKE_CXX_COMPILER="clang++-$CLANG_VERSION" \
            -D CMAKE_C_COMPILER="clang-$CLANG_VERSION"     \
            -D URI_FUZZTEST=Yes                            \
            -D URI_LIBCXX=Yes

      - name: Build
        run: |
          make -C "$BUILD_DIR" -j "$(nproc)"

      - name: Fuzz
        run: |
          "$BUILD_DIR/unittests/uri/unittest" --fuzz_for 30s
