name: Fuzz Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  fuzztest:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_fuzztest
      CLANG_VERSION: 15

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 cmake libc++-15-dev libc++abi-15-dev

      - name: Configure Build
        run: |
          mkdir "$BUILD_DIR"
          cmake                                            \
            -S .                                           \
            -B "$BUILD_DIR"                                \
            -D CMAKE_C_COMPILER="clang-$CLANG_VERSION"     \
            -D CMAKE_CXX_COMPILER="clang++-$CLANG_VERSION" \
            -D CMAKE_BUILD_TYPE=RelWithDebug               \
            -D URI_FUZZTEST=Yes                            \
            -D URI_LIBCXX=Yes

      - name: Build and Test
        run: |
            make -C "$BUILD_DIR" -j $(nproc)
