name: Fuzz Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  fuzztest:
    name: Fuzz Test
    runs-on: ubuntu-22.04

    env:
      BUILD_DIR: ./build_fuzztest
      CLANG_VERSION: 16

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install Dependencies (LLVM)
        uses: paulhuggett/install-llvm@ad897b4b1cf03f54c1218ec6d97a23ff4b10b870 # v1.0
        with:
          version: ${{ env.CLANG_VERSION }}

      - name: Configure
        run: |
          mkdir "$BUILD_DIR"
          cmake                                            \
            -S "$GITHUB_WORKSPACE"                         \
            -B "$BUILD_DIR"                                \
            -G "Unix Makefiles"                            \
            -D CMAKE_BUILD_TYPE=RelWithDebug               \
            -D "CMAKE_CXX_COMPILER=clang++-$CLANG_VERSION" \
            -D "CMAKE_C_COMPILER=clang-$CLANG_VERSION"     \
            -D URI_FUZZTEST=Yes

      - name: Build
        run: |
          make -C "$BUILD_DIR" -j "$(nproc)"

      - name: Fuzz
        run: |
          "$BUILD_DIR/unittests/uri/unittest" --fuzz_for 30s
