name: Fuzz Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  fuzztest:
    name: Fuzz Test
    runs-on: ubuntu-22.04

    env:
      BUILD_DIR: build_fuzztest
      CLANG_VERSION: 16

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install Dependencies (LLVM)
        uses: paulhuggett/install-llvm@cf3daa3e383020edd7db6a804b9b25335804ffbe # v0.1.1
        with:
          version: ${{ env.CLANG_VERSION }}

      - name: Configure
        run: |
          mkdir "$BUILD_DIR"
          cmake                                            \
            -S "$GITHUB_WORKSPACE"                         \
            -B "$BUILD_DIR"                                \
            -G "Unix Makefiles"                            \
            -D CMAKE_BUILD_TYPE=RelWithDebug               \
            -D "CMAKE_CXX_COMPILER=clang++-$CLANG_VERSION" \
            -D "CMAKE_C_COMPILER=clang-$CLANG_VERSION"     \
            -D URI_FUZZTEST=Yes

      - name: Build
        run: |
          make -C "$BUILD_DIR" -j "$(nproc)"

      - name: Fuzz
        run: |
          "$BUILD_DIR/unittests/uri/unittest" --fuzz_for 30s
